groups:
  - name: node-recording
    rules:
      - record: cpu_frequency
        expr: |
          avg by (instance) (node_cpu_scaling_frequency_hertz)
          or
          avg by (instance) (node_cpu_frequency_hertz)
          or
          avg by (instance) (cpu_frequency_hz)
